language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2.4
  - 2.3.0
  - ruby-head

gemfile:
  - gemfiles/Gemfile.rails-3.2
  - gemfiles/Gemfile.rails-4.0
  - gemfiles/Gemfile.rails-4.1
  - gemfiles/Gemfile.rails-4.2
  - gemfiles/Gemfile.rails-edge

sudo: false

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-edge
    - rvm: 2.1
      gemfile: gemfiles/Gemfile.rails-edge
    - rvm: 2.2.4
      gemfile: gemfiles/Gemfile.rails-3.2
    - rvm: 2.3.0
      gemfile: gemfiles/Gemfile.rails-3.2
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-3.2
  allow_failures:
    - rvm: ruby-head
